### ISSUE TITLE
Can you share your training video?

### ISSUE THREAD

**Issue by Lotayou** [nyoki-mtl/pytorch-EverybodyDanceNow#1]
Hi, it's good to see you reproducing this work, too. I'm wondering can you share your training video with me? It's difficult to find the suitable video data for this work and I would appreciate if you can provide me something like a YouTube link, thanks!

**Comment by nyoki-mtl** [comment]
@Lotayou 
[Here](https://drive.google.com/open?id=1Z7b3BWTWUxkwq0dUuUdgfkVTqtbVHUr6) is my train dataset.
But, I don't think it is suitable for this work.
I should increase the number of images and take more various poses.
I will remove the link in a week.

**Comment by Lotayou** [comment]
Thanks for the heads up. I'll keep on rolling with my work. Let's stay in touch and continue sharing info with each other. Good luck bro.

**Comment by nyoki-mtl** [comment]
Thanks!

**Comment by Lotayou** [comment]
I've finished downloading the dataset. Feel free to disable the link anytime. 

BTW, do you mind telling me how long does it take to train such a model (I have one Nvidia card with 12G memory)? I can use a rough timeline to coordinate with my colleagues.

Also, there's one thing puzzling me: It seems like pix2pixHD is designed to translate the segmentation masks to real images, not the skeleton stick-figures. Are we really supposed to use the skeleton as label instead of treating it as a normal RGB image from a different modality?

Anyway, I'll try using both body masks and image skeletons as input, gonna open a new repository on that too. I'll keep you notified if anything new happens.

**Comment by Lotayou** [comment]
Hey, any progress? I've successfully trained pix2pix model with my own dataset and will publish the result these days

**Comment by prismformore** [comment]
@Lotayou I think the input of pix2pixHD is RGB image in this code

**Comment by Lotayou** [comment]
@prismformore My thought exactly. using RGB input works well. It's just that nyoki's dataset convert skeleton to labels that I feel necessary to clarify this.

**Comment by prismformore** [comment]
@Lotayou Would u mind showing us your generated results with a comparison of different types of input (real image and skeleton)? Which one is better?

**Comment by Lotayou** [comment]
@prismformore I'll upload my own implementation in a matter of days...

**Comment by Lotayou** [comment]
@prismformore Sorry buddy, found some improvements when reproducing the work that I deem paper-worthy, so I'm probably not gonna release my implementation for now. Hope you understand.
